### ISSUE TITLE
Add isHorizontalScrollingEnabled option to mapView

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/mapbox-gl-native-ios#107]
This is a feature request for the ability to easily **_disable horizontal scrolling_**. It’s currently possible to do this by 1) restricting the bounds of the map (defining a northeast coordinate with a latitude of 90 and a southwest coordinate with a latitude of -90), but the scrolling behavior is not smooth. With this approach it’s necessary to swipe straight up and down or you bump into the east and west bounds. 

It’s also possible to disable horizontal scrolling 2) using a custom `UIPanGestureRecognizer`. This proves challenging as it’s necessary to figure out how to gradually decrease the speed of the scroll to mimic the default scroll behavior. 

It would be great to expose a simple option on the mapView for this behavior

cc @captainbarbosa

Android equivalent: https://github.com/mapbox/mapbox-gl-native-android/issues/105

**Comment by julianrex** [comment]
@captainbarbosa @malwoodsantoro can we mark this as closed?

**Comment by malwoodsantoro** [comment]
👍 This has been implemented https://github.com/mapbox/mapbox-gl-native-ios/pull/108
