### ISSUE TITLE
Evaluate committing the generate mbgl Xcode project

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#110]
If we commit the generated mbgl Xcode project (that's created by `make iproj`), we should be able to better support building from source without requiring tool dependencies (e.g. `cmake`).

We need to spend some time investigating this, as it will unlock supporting building with Carthage's `--no-use-binaries` option.

See also https://github.com/mapbox/mapbox-gl-native-ios/issues/109

**Comment by julianrex** [comment]
Things to consider:
- Converting absolute to relative paths
- Does this lock us to a particular Xcode version? Is that a problem?

**Comment by julianrex** [comment]
cc @nishant-karajgikar

**Comment by 1ec5** [comment]
> Does this lock us to a particular Xcode version? Is that a problem?

No, Xcode is very lenient about project format versions. Xcode 11 can still open projects generated in something like Xcode 4 or 5. If anything, building from source makes us more flexible in terms of Xcode versions.

**Comment by knov** [comment]
cc @misterkerry

**Comment by julianrex** [comment]
This is no longer valid.
