### ISSUE TITLE
mbgl/util/chrono.hpp' file not found

### ISSUE THREAD

**Issue by dream5788** [mapbox/mapbox-gl-native-ios#111]
mbgl/util/chrono.hpp' file not found

Can not run

### Steps to reproduce

 1.
 2.
 3.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by julianrex** [comment]
@dream5788 unfortunately there is not enough information here about: your setup, how you're compiling the SDK, which version of the SDK you're trying to compile and whether you have [installed the required dependencies](https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/INSTALL.md). 

Until we have this information, we cannot help debug your issue; I'm going to close this issue. If you can provide this information, please feel free to re-open.

It may help to read the [README.md](https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/README.md) and [DEVELOPING.md](https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/DEVELOPING.md).
