### ISSUE TITLE
Can not compile SDK

### ISSUE THREAD

**Issue by lcf001** [mapbox/mapbox-gl-native-ios#112]
### Steps to reproduce

 I followed the steps to compile the mapbox-gl-native on MacOS but I got this error when I try to compile from terminal: make iframework BUILDTYPE=Release

make: *** No rule to make target `vendor/mapbox-gl-native/Makefile', needed by `'build/ios/Mapbox'.  Stop.
 

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by shorben07** [comment]
Try to run `git submodule update --init --recursive` in Terminal
