### ISSUE TITLE
Failed to bind EAGLDrawable to GL_RENDERBUFFER 1

### ISSUE THREAD

**Issue by JimRoepcke** [mapbox/mapbox-gl-native-ios#113]
I tried the Mapbox SwiftUI demo code, and it was working until today. Now, on the simulators of two different Macs and an iPhone 11 all cannot render a Mapbox GL map.

I thought maybe some changes I made to the demo code caused the problem, but even when I used the demo code exactly it still fails in this manner.

Again, this was working well on Monday, the last time I remember running it.

```
2019-12-18 13:02:34.817349-0800 MGLTest[432:30871] Metal API Validation Enabled
2019-12-18 13:02:35.000006-0800 MGLTest[432:30871] MGLMapView WARNING UIViewController.automaticallyAdjustsScrollViewInsets is deprecated use MGLMapView.automaticallyAdjustContentInset instead.
2019-12-18 13:02:35.101485-0800 MGLTest[432:30871] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x2816fc1e0> to GL_RENDERBUFFER 1
2019-12-18 13:02:35.101594-0800 MGLTest[432:30871] Failed to make complete framebuffer object 8cd6
```

I can send someone my MGLTest sample project if they'd like to see it.

### Steps to reproduce

 1. Embed the Mapbox SDK to a new Xcode project and add the run script build phase to strip frameworks.
 2. Copy the contents of [ContentView.swift and MapView.swift](https://github.com/mapbox/mapbox-maps-swiftui-demo/) into the new project.
 3. Run the app.

### Expected behavior

I should see a map.

### Actual behavior

I see a white screen with a Mapbox logo at the bottom left and an "i" button at the bottom right.

### Configuration

**Mapbox SDK versions:** 5.5.0, and version.txt from the download contains https://github.com/mapbox/mapbox-gl-native-ios/commit/e495c1208f
**iOS/macOS versions:** iOS 13.1.3, iOS 13.1
**Device/simulator models:** iOS 13.1.3 iPhone 11, iOS 13.1 iPhone 8
**Xcode version:** 11.2.1

**Comment by JimRoepcke** [comment]
PEBCAK

**Comment by aaesis** [comment]
As of the moment I also have this kind of issue, Any clue howd it fixed?
