### ISSUE TITLE
How to fit bounds for all the markers with mapbox sdk for iOS?

### ISSUE THREAD

**Issue by hojatdelfan** [mapbox/mapbox-gl-native-ios#118]
How to fit bounds for coordinate array with apbox sdk for iOS? I need to zoom map for 4 visible markers(annotations) and above. I have not yet found a function that dynamically adds different points for bounding.

```
let origin = CLLocationCoordinate2DMake(lat, lng)
let destination_1 = CLLocationCoordinate2DMake(lat, lng)
let destination_2 = CLLocationCoordinate2DMake(lat, lng)
let destination_3 = CLLocationCoordinate2DMake(lat, lng)
var bound = MGLCoordinateBounds(sw: origin, ne: destination_1))
```
**We need a comprehensive solution that can dynamically add the rest of the points.**

**Comment by jmkiley** [comment]
Hi @hojatdelfan - 

Thank you for using Mapbox! Could you tell me a little more about what you are trying to do? If you would like to ensure that the map view shows four specific annotations, [`-showAnnotations:animated:`](https://docs.mapbox.com/ios/api/maps/5.6.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)showAnnotations:animated:) or [`-showAnnotations:edgePadding:animated:completionHandler:`](https://docs.mapbox.com/ios/api/maps/5.6.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)showAnnotations:edgePadding:animated:completionHandler:) may work for your use case.

**Comment by hojatdelfan** [comment]
Hi @jmkiley
The answer to my problem was that you said
```
guard let annotations = mapView.annotations else {return} // get all annotation(markers on the mapview)
mapView.showAnnotations(annotations, edgePadding: padding, animated: true, completionHandler: nil)
```
