### ISSUE TITLE
ios run crash

### ISSUE THREAD

**Issue by cocfident** [mapbox/mapbox-gl-native-ios#120]
use CocoaPods install SDK  when i run on Xcode cash with log  

dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /private/var/containers/Bundle/Application/6C54BD76-3526-46E6-8CA2-5BD0CA03A849/Runner.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found

**Comment by abrahamhunt** [comment]
Same issue with manual installation. It looks like the release package doesn't contain the new framework.

**Comment by abrahamhunt** [comment]
Release notes include this new information:
```Integrates MapboxMobileEvents as a dependency (#60). As a result, the following installation processes have changed:
CocoaPods: You now must include use frameworks! in your Podfile.
Carthage: Specify github "mapbox/mapbox-events-ios" == 0.10.2 in your Cartfile. Additionally, please note that if you are using --no-use-binaries, the MapboxMobileEvents.framework will still be installed as a dynamic framework.
Manual installation: New Github release artifact (mapbox-ios-sdk-5.6.0-beta.1-dynamic-with-events.zip) contains the MapboxMobileEvents.framework; please install this along with Mapbox.framework
```
I had to get the dynamic build from the release on Github and is is working now that I included both Frameworks. The website should use the new package now but has the old package without the events framework.

**Comment by nishant-karajgikar** [comment]
Hi @cocfident, as @abrahamhunt pointed out there have been some [changes](https://github.com/mapbox/mapbox-gl-native-ios/pull/60) in the way the Mapbox Telemetry SDK is integrated with the Mapbox SDK. Since we are now consuming the Telemetry SDK as a dynamic framework, you will need to add `use_frameworks!` at the top of your Podfile.
