### ISSUE TITLE
Spurious message about new SDK version being available

### ISSUE THREAD

**Issue by clydebarrow** [mapbox/mapbox-gl-native-ios#126]
iOS SDK on startup logs a message about a new version being available when it is not yet released.
### Steps to reproduce

 1. Build an app with Mapbox SDK for iOS V5.4.0.
 2. Run the app
 3. Examine the messages logged via the Foundation logger.

### Expected behavior
Nothing unusual

### Actual behavior
This message appears:
`Mapbox Maps SDK for iOS version 5.5.0 is now available: https://github.com/mapbox/mapbox-gl-native/releases/tag/ios-v5.5.0`

Not only is 5.5.0 not available (it's still in alpha) but if the link given is a non existent page (404 error from Github.)

### Suggested resolution

Inhibit messages about unreleased versions of the SDK. 

### Configuration

**Mapbox SDK versions:** 5.4.0
**iOS/macOS versions:** Any.
**Device/simulator models:** Any
**Xcode version:** Any

**Comment by julianrex** [comment]
Thanks for the report @clydebarrow - this was a URL that was overlooked in the recent migration of iOS & macOS platform code to this (https://github.com/mapbox/mapbox-gl-native-ios) repo.
