### ISSUE TITLE
About sdk compilation issues

### ISSUE THREAD

**Issue by lcf001** [mapbox/mapbox-gl-native-ios#129]
### Steps to reproduce
Now the latest release is v5.6.0，but I compile as follows, the result is always v5.6.0-alpha.2，why?
 1.git clone https://github.com/mapbox/mapbox-gl-native-ios.git
 2.cd mapbox-gl-native-ios
 3.git submodule update --init --recursive
 4.make iframework BUILDTYPE=Release

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
Xcode version:11.3

**Comment by julianrex** [comment]
Beta and stable releases are made from tagged release branches, most recently `release-tequila`. Alpha releases are made from `master` - which is why you're seeing `v5.6.0-alpha.2`.

Try cloning/checkout the latest tag `ios-v5.6.0`.
