### ISSUE TITLE
[IOS] MGLSymbolStyleLayer text will not display if it contains letters or Numbers

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-native-ios#137]
Platform: iOS
Mapbox SDK version: 5.5.0
Xcode version: Version 10.1 (10B61)
Devicemodels: iPad mini 3

Steps to trigger behavior:

1.I used GEOSwiftMapboxGL to convert the WKT into the pointAnno object of the MapBox through traversal.
2.The pointAnno data is then converted into an MGLPointFeature object and stored in an array.
3.Display the text label by generating MGLShapeSource and MGLSymbolStyleLayer.

<img width="1260" alt="屏幕快照 2019-12-20 下午5 45 57" src="https://user-images.githubusercontent.com/15685672/71245900-a7ee7580-2350-11ea-8d85-24411d839693.png">

<img width="1273" alt="屏幕快照 2019-12-20 下午5 34 49" src="https://user-images.githubusercontent.com/15685672/71245159-19c5bf80-234f-11ea-948d-c0e647682831.png">

### Expected behavior

Display all text on the map.

### Actual behavior

1.When mglshapesource.text = @ "测试" shows,
2.When mglshapesource.text = @ "测试 123" does not display
3.When mglshapesource.text = @ "测试 ABC" is not displayed

and
When text can be displayed, it is displayed at level >12, <12 is not displayed.

//1
![4BFC136E5413ADCD1AD89360C72B3992](https://user-images.githubusercontent.com/15685672/71245379-8476fb00-234f-11ea-9112-10283a4f9844.png)

//2,3
![8FDBE3C74AAA24571A1510BC63299E5C](https://user-images.githubusercontent.com/15685672/71245383-86d95500-234f-11ea-81f9-59a3f2d0efdf.png)

**Comment by jmkiley** [comment]
Tracking in #122
