### ISSUE TITLE
ld:library not found for -lmbgl-vendor-icu

### ISSUE THREAD

**Issue by lcf001** [mapbox/mapbox-gl-native-ios#145]
### Steps to reproduce
When I build the Mapbox Maps SDK for iOS from source,I get the following error:
 ld:library not found for -lmbgl-vendor-icu
 where do I set it?
### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by nishant-karajgikar** [comment]
Have you updated your submodules using `git submodule update --init --recursive`?

**Comment by lcf001** [comment]
@nishant-karajgikar  Yes, I did. Then I create and open an Xcode workspace to build the sdk and got this error。

**Comment by nishant-karajgikar** [comment]
Okay, I see. That library is built by running `make iframework` (before you open the workspace).  Please follow the instructions here - https://github.com/mapbox/mapbox-gl-native-ios/blob/master/platform/ios/INSTALL.md

**Comment by nishant-karajgikar** [comment]
Closed this ticket since those instructions should have fixed the problem. Please reopen if you're still running into it.
