### ISSUE TITLE
Add podspec run script / runtime check to ensure inclusion of the MapboxMobileEvents framework

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#156]
See https://github.com/mapbox/mapbox-gl-native-ios/pull/150 and especially [this comment](https://github.com/mapbox/mapbox-gl-native-ios/pull/150#pullrequestreview-344934268).

The run script would only affect Cocoapods (though still worth doing). The runtime check should give the developer clearer instructions, rather than just seeing a confusing dynamic library load failure.

**Comment by 1ec5** [comment]
> The runtime check should give the developer clearer instructions, rather than just seeing a confusing dynamic library load failure.

In my opinion, the instructions in and of themselves don’t merit complicating the build system. We can always publish a troubleshooting document for things that can go wrong at launch.

**Comment by julianrex** [comment]
Closing as stale.
