### ISSUE TITLE
Unable to display MGLAnnotationView on iOS 13 (Xcode 11)

### ISSUE THREAD

**Issue by aoapnl** [mapbox/mapbox-gl-native-ios#158]
I'm trying to create a custom annotation view to add to my map. I have never been able to make it work with iOS 13 and Xcode 11.

I tried to use example codes from your documentation but it still doesn't show anything. Surprisingly, I can tap where my annotation is supposed to be displayed to select it.

If I put a brakepoint in `mapView(_ mapView: MGLMapView, didSelect annotation: MGLAnnotation)` after getting the view for my annotation, I can see it perfectly with Quick Look.

The frame is also correct : `<MGLAnnotationView: 0x7fa221c06fb0; frame = (172.5 328.5; 30 30); layer = <CALayer: 0x60000139df20>>`

I ended up executing my code on iOS 12 and it worked.

I also tried to compile with Xcode 10.3 by copy-pasting iOS 13.X DeviceSupports folders in its package so I can compile on a iOS 13 device with Xcode 10.3 and it worked.

In a nutshell, the issue happens when compiling with Xcode 11 and running on iOS 13.

### Steps to reproduce

Here is a code that reproduces the issue. It's basically an example code I found in the documentation.

```
import Mapbox

class MyCustomPointAnnotation: MGLPointAnnotation {
    var willUseImage: Bool = false
}

class ViewController: UIViewController, MGLMapViewDelegate {

    let paris = CLLocationCoordinate2D(latitude: 48.853, longitude: 2.35)

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Create a new map view using the Mapbox Light style.
        let mapView = MGLMapView(frame: view.bounds, styleURL: MGLStyle.lightStyleURL)
        
        mapView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        // Set the map’s center coordinate and zoom level.
        mapView.setCenter(paris, zoomLevel: 9, animated: false)
        view.addSubview(mapView)
        mapView.delegate = self
        
        // Create four new point annotations with specified coordinates and titles.
        let pointA = MyCustomPointAnnotation()
        pointA.coordinate = paris
        pointA.title = "Paris"
        pointA.willUseImage = true
        
        // Add all annotations to the map all at once, instead of individually.
        mapView.addAnnotation(pointA)
    }
    
    // This delegate method is where you tell the map to load a view for a specific annotation based on the willUseImage property of the custom subclass.
    func mapView(_ mapView: MGLMapView, viewFor annotation: MGLAnnotation) -> MGLAnnotationView? {
        
        guard annotation is MyCustomPointAnnotation else {
            return nil
        }
        
        // Assign a reuse identifier to be used by both of the annotation views, taking advantage of their similarities.
        let reuseIdentifier = "reusableDotView"
        
        // For better performance, always try to reuse existing annotations.
        var annotationView = mapView.dequeueReusableAnnotationView(withIdentifier: reuseIdentifier)
        
        // If there’s no reusable annotation view available, initialize a new one.
        if annotationView == nil {
            annotationView = MGLAnnotationView(reuseIdentifier: reuseIdentifier)
            annotationView?.frame = CGRect(x: 0, y: 0, width: 30, height: 30)
            annotationView?.layer.cornerRadius = (annotationView?.frame.size.width)! / 2
            annotationView?.layer.borderWidth = 4.0
            annotationView?.layer.borderColor = UIColor.white.cgColor
            annotationView?.backgroundColor = UIColor(red: 0.03, green: 0.80, blue: 0.69, alpha: 1.0)
        }
        
        return annotationView
    }
    
}
```

### Expected behavior

The annotation should be visible.

### Actual behavior

With Xcode 11 and iOS 13, the annotation is not visible but still selectable.

### Configuration

**Mapbox SDK versions:** Reproduced with version 5.6.1, 5.7.0-beta.1 and 5.1.0
**iOS/macOS versions:** Reproduced with iOS 13.2 and iOS 13.3. Works on iOS 12 (tested 12.3.1 and 12.4)
**Device/simulator models:** XR, X (iOS 13), 6 (iOS 12.3.1) and simulators.
**Xcode version:** 11.3 (doesn't work on iOS 13), 10.3 (works with iOS 13)

**Comment by jmkiley** [comment]
Hello @aoapnl -

Thanks for the report and sample code. I ran your sample code with Xcode 11.3.1 and 11.2.1 on an iPhone X and iPhone 11 Pro, but wasn't able to see this issue with iOS 13.3.1.  I'm also able to see the annotation on simulators. Are you seeing any console output when you run the app?

**Comment by aoapnl** [comment]
Hello. Sorry for the late reply.

I actually can't reproduce the issue anymore. I'm not sure what changed since the last time. I had already cleaned my project and the derived data several times. I was stuck on this issue for hours, but I never found a way to fix it.

I'll let you know if the issue comes back, but I'd be surprised.

Thanks for your time.
