### ISSUE TITLE
Do you have a open-source of China plugins for IOS?

### ISSUE THREAD

**Issue by lily0101** [mapbox/mapbox-gl-native-ios#161]
hi,
I found the document of Mapbox China plugin for iOS , but I don't see the same project in git, do you have opened the project ?  I found an experimental project in [here,](https://github.com/mapbox/mapbox-plugins-ios) 
but it seems not  the China plugin to support China. I want to know how to shift WGS-84 coordinates to GCJ-02 according the government's requirements.
Please tell me if you know it! 
Thanks so much.

**Comment by Jing-flyloveyin** [comment]
Hi @lily0101 Thanks for your question. Please check this blog in Chinese: https://mp.weixin.qq.com/s?__biz=MzIwNTU1MDM2Mg==&mid=2247486240&idx=1&sn=760f034ab6bd1975c00ad0273aa4cbf5&chksm=972e6d55a059e44334f48bd5bf92bccc6129754808c8ba686815b0cc9c2192f468cab8516492&token=1403949756&lang=zh_CN#rd

**Comment by julianrex** [comment]
Closing as answered.
