### ISSUE TITLE
Carthage installs of SDK are broken

### ISSUE THREAD

**Issue by jwoyame** [mapbox/mapbox-gl-native-ios#166]
This isn't strictly related to the open source project, but I thought it important to document for people with the issue.

There is a formatting error with the https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json file. Notice at the end of the second to last line, there is an accidental backtick character:

`` "3.1.0-pre.1": "https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.1.0-pre.1-dynamic.zip"` ``

This breaks all Mapbox iOS product installs with the following error:

`Unable to parse binary-only framework JSON at https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Badly formed object around character 22379." UserInfo={NSDebugDescription=Badly formed object around character 22379.})))`

**Comment by captainbarbosa** [comment]
Hi @jwoyame! Sorry about that, we made an accidental typo when updating that file for today's release. We've got an internal PR ready for review now, it should be fixed by tomorrow. Thanks!

**Comment by 1ec5** [comment]
The syntax error should be fixed now. We’re also working on an internal change that’ll prevent this error from occurring in the future. Sorry for the inconvenience!

**Comment by jwoyame** [comment]
I can confirm it's working fine, thank you!!!
