### ISSUE TITLE
testContentInsetCenter & testContentInsetOrnaments fail on iPhone X

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#167]
The following unit tests are failing on an iPhone X simulator in `release-unicorn`:

- `testContentInsetCenter`
    At first glance, this appears to be an assumption in the test, that the top and bottom content insets are equal.

- `testContentInsetOrnaments`
    Although `contentInset` is set to 0, `automaticallyAdjustsContentInset` is `YES`, so will be reset to the safe insets (IIRC). However, even if this is set to `NO` the ornament constraints are still relative to the safe insets.

EDIT: Worth noting that these tests pass on an iPhone 8, which happens to be the device used in CI, hence why we haven't seen this fail PRs.

/cc @fabian-guerra @astojilj

**Comment by julianrex** [comment]
cc @jmkiley

**Comment by 1ec5** [comment]
This issue reproduces in the wild: mapbox/mapbox-navigation-ios#2353.
