### ISSUE TITLE
Add expression "in"

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native-ios#168]
The core sdk implemented a new `in` expression in https://github.com/mapbox/mapbox-gl-native/pull/16162. This ticket will track the implementation of the corresponding iOS bindings.

For reference, this is the Android implementation: https://github.com/mapbox/mapbox-gl-native-android/pull/171

/cc @mapbox/maps-ios

**Comment by 1ec5** [comment]
I think the most natural NSExpression implementation of this expression operator would be `needle IN haystack` (alternatively `haystack CONTAINS needle`), where `haystack` is an aggregate expression, constant expression of type NSArray or NSSet, or NSString.

NSComparisonPredicate+MGLAdditions already implements `IN` and `CONTAINS` as syntactic sugar for `MGL_MATCH`, for example translating `$geometryType IN {'LineString', 'Polygon'}` as `['match', ['geometry-type'], ['LineString', 'Polygon'], true, false]`. I think we can now eliminate this syntactic sugar in favor of the more generalized `in` operator support in mbgl.

As always, if the developer needs something syntactically closer to JSON, they can use `MGL_FUNCTION()` or `+[NSExpression expressionWithJSONObject:]`.

**Comment by 1ec5** [comment]
We currently document supporting NSExpression’s `[c]` and `[d]` modifiers “for comparison and aggregate operators”, but `in` is the one comparison operator for which the style specification doesn’t allow customizing case or diacritic sensitivity: mapbox/mapbox-gl-js#9339. For now, we’ll have to document this exception for the `IN` and `CONTAINS` operators.

**Comment by 1ec5** [comment]
This feature depends on [gl-native v1.2.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/maps-v1.2.0).
