### ISSUE TITLE
Update Transifex for new repo

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-gl-native-ios#17]
- [ ] Update Transifex paths.

We should make sure Transifex is set up and working with this repo

**Comment by 1ec5** [comment]
#93 removed Android resources from the Transifex configuration file. The iOS and macOS resources have remained at the same paths as before. The URLs that Transifex watches for changes were also updated at around the same time. I think that should take care of keeping the localization workflow running smoothly, unless we want to split the iOS map SDK out of the [Mapbox GL Native project](https://www.transifex.com/mapbox/mapbox-gl-native/dashboard/) on Transifex.
