### ISSUE TITLE
Platform bindings for `within` expression

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-ios#175]
Tracking the development of platform bindings for the new `within` expression (https://github.com/mapbox/mapbox-gl-native/pull/16157; https://github.com/mapbox/mapbox-gl-native/pull/16194)

If it's possible, because this isn't too complex, it would be great to get this merged this week before the next `alpha` release.

cc @julianrex @zmiao

**Comment by 1ec5** [comment]
I think the most natural NSExpression implementation of this expression operator would be `SELF IN %@` (alternatively `%@ CONTAINS SELF`), where `%@` is an MGLFeature. As always, if the developer needs something syntactically closer to JSON, they can use `MGL_FUNCTION()` or `+[NSExpression expressionWithJSONObject:]`.

**Comment by 1ec5** [comment]
We currently document supporting NSExpression’s `[c]` and `[d]` modifiers “for comparison and aggregate operators”, but `in` is the one comparison operator for which the style specification doesn’t allow customizing case or diacritic sensitivity: mapbox/mapbox-gl-js#9339. For now, we’ll have to document this exception for the `IN` and `CONTAINS` operators.

**Comment by 1ec5** [comment]
This feature depends on [gl-native v1.2.0](https://github.com/mapbox/mapbox-gl-native/releases/tag/maps-v1.2.0).

**Comment by zmiao** [comment]
@1ec5 here is the Android binding for `within` expression, please have a look https://github.com/mapbox/mapbox-gl-native-android/pull/198/files, please be aware currently `toGeoJSON` is not implemented in MGLConversion.h, it also caused problems with android_conversion.hpp, extra adaptation is done in https://github.com/mapbox/mapbox-gl-native/pull/16243
