### ISSUE TITLE
Platform bindings for source.setPrefetchZoomDelta

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-native-ios#177]
The range of zoom levels to include in tile prefetching can now be adjusted by `source` (overriding the `map` setting) in mbgl.

https://github.com/mapbox/mapbox-gl-native/pull/16179

cc @1ec5 @mapbox/maps-ios

**Comment by 1ec5** [comment]
mapbox/mapbox-gl-native#16179 was released in gl-native v1.3.0, so this feature depends on #181.
