### ISSUE TITLE
git submodule update so slow

### ISSUE THREAD

**Issue by fanmaoyu0871** [mapbox/mapbox-gl-native-ios#201]
hi, i am in china. i want to build ios framework, i had  finished `git clone`, then i do `git submodule update --init --recursive`, it download very slow, and offen disconnect. i have retry sometimes! it's so mess.Do you have other way to download the source of mapbox.Thanks!

**Comment by captainbarbosa** [comment]
Hi @fanmaoyu0871 - some level of slowness is to be expected. Several developers who had experienced similar issues when trying to build this framework have reported success in using a VPN. You may want to try this and see if it helps.
