### ISSUE TITLE
MGLCircleStyleLayer.circleColor not been set correctly with feature's property 

### ISSUE THREAD

**Issue by mrcrow** [mapbox/mapbox-gl-native-ios#202]
Hi, In my case, I want to display points with different color on the map.

The data source is a geojson file with a collection of point features, each feature has a property named `color` with hex format color string aimed to setup the `circleColor` with an simple `[NSExpression expressionForKeyPath:` expression. However, it doesn't work like `MGLFillExtrusionStyleLayer`'s `fillExtrusionColor`, the hex string are not been converted to an `UIColor` instance.

So any one can help?
Thanks!

**Comment by captainbarbosa** [comment]
Hey @mrcrow - can you provide a short minimal test case that reproduces what you're seeing? Thanks!

**Comment by mrcrow** [comment]
@captainbarbosa Hey, thanks for your replay

I don't know how to make a test case to you, the logic is contained in a huge project, the only thing that I can explore to you is the GeoJSON sample data retrieved from API

```
{
    features =     (
                {
            geometry =             {
                coordinates =                 (
                    "118.9162007407753",
                    "32.11524253749015"
                );
                type = Point;
            };
            properties =             {
                color = "#EFECE4";
                name = "Door 001";
                type = door;
                zoom = 18;
            };
            type = Feature;
        }
    );
    type = FeatureCollection;
}
```

After that, the JSON object will be converted to `NSData` and construct `MGLShape` as the source of style layer, anything goes well except the color.

Does this help?

**Comment by captainbarbosa** [comment]
Okay thanks. Can you provide the full `NSExpression` you're using? I think that should be enough.

**Comment by mrcrow** [comment]
No problem, the context is as follow

```
NSString *sourceID = @"circle-source";
MGLSource *source = [[MGLShapeSource alloc] initWithIdentifier:sourceID shape:shape options:nil];
[_mapView.style addSource:source];

NSString *circleLayerID = @"circle-layer";
MGLCircleStyleLayer *circleLayer = [[MGLCircleStyleLayer alloc] initWithIdentifier:circleLayerID source:source];
circleLayer.sourceLayerIdentifier = circleLayerID;
circleLayer.minimumZoomLevel = 17;
circleLayer.circleColor = [NSExpression expressionForKeyPath:@"color"];
circleLayer.circleRadius = [NSExpression expressionForConstantValue:@4];
circleLayer.circleStrokeColor = [NSExpression expressionForConstantValue:[UIColor whiteColor]];
circleLayer.circleStrokeWidth = [NSExpression expressionForConstantValue:@1];
circleLayer.circleOpacity = [NSExpression expressionWithFormat:@"mgl_step:from:stops:($zoomLevel, 1, %@)", @{@17 : @1, @18 : @0}];
circleLayer.circleStrokeOpacity = circleLayer.circleOpacity;
[_mapView.style addLayer:circleLayer];
```

**Comment by captainbarbosa** [comment]
@mrcrow Okay thanks for that - we've added it to our triage queue.

**Comment by mrcrow** [comment]
> @mrcrow Okay thanks for that - we've added it to our triage queue.

Thank you @captainbarbosa

**Comment by mrcrow** [comment]
@captainbarbosa any update here？

**Comment by mrcrow** [comment]
I would like to close this issue, because this no longer an issue after go through the property usage. A `CAST()` function has already archieved the goal
