### ISSUE TITLE
The logic for checking whether telemetry opt-out control is missing may contain a bug

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-gl-native-ios#212]
In MGLMapboxEvents.m, it seems that ensureMetricsOptoutExists wants to ensure that the default value of MGLMapboxMetricsEnabled is true. But currently it only raises exception if there is no default value, it will not raise exception if the default value is false.

Maybe, it needs to check [defaultEnabledValue boolValue] too.

**Mapbox SDK versions:** 5.8.0-alpha.1

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapbox-gl-native-ios/blob/f08955e2ce07cb854e52beeb466c550fe26d4928/platform/ios/src/MGLMapboxEvents.m#L193-L211

**Comment by ystsoi** [comment]
Yes, I refer to this part. Maybe,
```
 if (!defaultEnabledValue || ![defaultEnabledValue boolValue]) {
```
should be used instead of
```
 if (!defaultEnabledValue) {
```
It seems that just checking defaultEnabledValue is not enough to ensure that the default value is true, as mentioned in:
https://docs.mapbox.com/help/how-mapbox-works/attribution/#mapbox-maps-sdk-for-ios

Of course, I want to set the default value to false, but if this is a requirement, then clearer is better.

**Comment by chloekraw** [comment]
@ystsoi thanks for flagging. We'll make this adjustment in this release to clarify our expectations.
