### ISSUE TITLE
Add a flag to pause network requests

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#217]
This issue is for tracking the continuation/porting of https://github.com/mapbox/mapbox-gl-native/pull/15650. See https://github.com/mapbox/mapbox-gl-native/issues/7443 for the original issue.

@fabian-guerra @knov let's evaluate if this is still needed.

**Comment by VitaliiTokar** [comment]
Hello my name is Vitalii Tokarenko) I love human

**Comment by julianrex** [comment]
See https://github.com/mapbox/mapbox-gl-native-ios/issues/309 for a recent duplicate, and a possible option: https://github.com/trailbehind/mapbox-gl-native-ios/pull/1
