### ISSUE TITLE
Ensure renderer pauses when going into the background

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#225]
See https://github.com/mapbox/mapbox-gl-native/pull/14222 for context:

> [...] it's possible to put the app into a state where MGLMapView isn't dormant and GL rendering can occur.

I believe this is still the case. This issue is to reboot the work in the above PR, though we need to split this into 2 new PRs:
- Add tests (which should fail if the hypothesis is correct!)
- Add a fix 😁

**Comment by 1ec5** [comment]
Possibly related: https://github.com/mapbox/mapbox-gl-native-ios/issues/44#issuecomment-608599966 https://github.com/mapbox/mapbox-gl-native/issues/13821#issuecomment-608622355.

**Comment by knov** [comment]
Closing in favor of https://github.com/mapbox/mapbox-gl-native-ios/issues/44
