### ISSUE TITLE
Uncaught exception starting MGLMapSnapshotter before using MGLMapView or MGLOfflineStorage

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native-ios#227]
If an application attempts to take a snapshot before ever initializing an MGLMapView or interacting with MGLOfflineStorage directly, `-[MGLMapSnapshotter startWithQueue:overlayHandler:completionHandler:]` raises an exception:

https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L267-L270

This check is premature, since the method soon afterwards causes MGLOfflineStorage to create an `mbgl::util::RunLoop` and various file sources on the current thread:

https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L285 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLMapSnapshotter.mm#L664 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLOfflineStorage.mm#L64 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLOfflineStorage.mm#L223 https://github.com/mapbox/mapbox-gl-native-ios/blob/81df48df70ad6b116f3f17321d11a56a03b3cc3e/platform/darwin/src/MGLFoundation.mm#L5

If we were to simply remove or defer this check, the check would pass even if starting the snapshotter on a background thread. However, the static `mbgl::util::RunLoop` intended for the main thread would be created for a background thread, which would lead to undefined behavior, for example when subsequently using MGLMapView.

Before #210, the same application didn’t trigger the exception because `-[MGLMapSnapshotter initWithOptions:]` happened to call `-setOptions:`, which called `+[MGLOfflineStorage sharedOfflineStorage]` before the run loop check. Even so, if a developer happened to initialize the snapshotter on a background thread, the static `RunLoop` intended for the main thread would’ve been created on the background thread.

One potential fix would be to call `+[MGLOfflineStorage sharedOfflineStorage]` in `+[MGLMapSnapshotter initialize]`, but that could potentially impact startup time even in applications that don’t use MGLMapSnapshotter earlly on. Another fix would be to replace the existing check with one that explicitly raises an exception if it’s on a background thread but calls `+[MGLOfflineStorage sharedOfflineStorage]` if it’s on the main thread.

Thanks to @julianrex for spotting and helping to diagnose this issue.

/cc @mapbox/maps-ios @alexshalamov

**Comment by chloekraw** [comment]
@1ec5 @julianrex is this issue fixed with #227?

**Comment by 1ec5** [comment]
No, that was a workaround in an internal testing repository. (The workaround is to call `+[MGLOfflineStorage sharedOfflineStorage]` pro forma before creating a snapshotter.)
