### ISSUE TITLE
userLocationAnnotation offset from road network with .followWithHeading tracking mode 

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/mapbox-gl-native-ios#238]
I encountered strange behavior with the followWithHeading tracking mode: when using `.followWIthHeading`, the userLocationAnnotation is seen as far off the road network, but when the tracking mode is set to none, the annotation moves fine along the road network. 

### Steps to reproduce

 1. run the[ switch between user modes](https://docs.mapbox.com/ios/maps/examples/user-tracking-mode/) example
 2. set tracking mode to `.followWithHeading`
 3. observe userLocationAnnotation behavior

### Expected behavior

I expect the userLocationAnnotation to follow the road network regardless of the tracking mode selected.

### Actual behavior

| no tracking mode selected:  | followWithHeader tracking mode: |
| ------------- | ------------- |
| ![none](https://user-images.githubusercontent.com/44972592/77485464-990dd800-6e03-11ea-8d7a-d4c767048fcf.gif)  | ![followWithHeader](https://user-images.githubusercontent.com/44972592/77485469-9ad79b80-6e03-11ea-91a7-f031527e3910.gif) |

### Configuration

**Mapbox SDK versions:** 5.7.0
**iOS/macOS versions:** iOS 13.3.1
**Device/simulator models:** iPhone 11 pro
**Xcode version:** 11.3.1

**Comment by 1ec5** [comment]
Does the issue persist if you hold still and avoid rotating the phone? If so, this is caused by mbgl’s inability to perform two distinct animations (rotation and panning) concurrently, as described in https://github.com/mapbox/mapbox-gl-native/issues/3625#issuecomment-173128298.

**Comment by georgbachmann** [comment]
I am also seeing the issue and as @1ec5 pointed out, it's not a problem any more, when holding the device still. But isn't there any other possibility to fix this? It's a bit hard to tell all my users that they are just holding it wrong ;) and need to hold still in order for my map to properly function :(
