### ISSUE TITLE
Release script depends on deprecated GitHub API

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native-ios#265]
Both the iOS and macOS versions of deploy-packages.sh depend on the [`github-release`](https://github.com/aktau/github-release/) tool to upload releases. This tool relies on an authentication mechanism in the GitHub API that [has been deprecated](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters).

GitHub has started [getting more aggressive](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) about migrating developers off the deprecated authentication mechanism, including sending me an e-mail every time I run the macOS deployment script on my machine. (The iOS script also triggers these e-mails, but I don’t think MapboxCI is keeping up with its inbox these days.) There are brownout periods scheduled, and the deprecated functionality will be removed outright later this year.

aktau/github-release#97 tracks this issue in the context of the `github-release` tool. The official tool is no longer maintained, but some of its forks have apparently been patched. This might be a good opportunity to research alternative tools like `hub` that, despite being more full-featured than we need, do enjoy active maintenance.

/cc @mapbox/maps-ios

**Comment by nishant-karajgikar** [comment]
This is unfortunate. I looked at those forks and while some of them do seem to have claimed to patch it, there are some conflicting reports about whether or not they've actually fixed it. 

[`Hub`](https://github.com/github/hub) is probably our best option. It has a [`hub-release`](https://github.com/github/hub) command that we could leverage.

I have, however, read some reports that `hub` will soon be replaced by the official [CLI](https://cli.github.com). The official CLI does not yet expose a way to manage github releases (but there is an [open feature request](https://github.com/cli/cli/issues/378)) unfortunately, so we may be looking at a short term move to Hub and then over to the CLI (once it adds the capability).

**Comment by knov** [comment]
Noting that per the above links, Github CLI will be out of beta "likely toward the end of 2020"

**Comment by 1ec5** [comment]
github-release/github-release@164ff3aa40669e68668d460d986cc89f5e654140 migrated to basic authentication, and the fix made it into github-release v0.8.0. Homebrew has picked up this release (as well as a newer one), so CircleCI builds are already using the newer version, and I’ve upgraded my own machine for macOS releases.
