### ISSUE TITLE
snapshot not correct

### ISSUE THREAD

**Issue by MaYanpeng** [mapbox/mapbox-gl-native-ios#270]
### Steps to reproduce

 1.run the demo(iOS simulator) --> show Snapshots
 2. some pictures are not show
 3.

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** 
**Device/simulator models:**
**Xcode version:**

**Comment by 1ec5** [comment]
Given https://github.com/mapbox/mapbox-gl-native-ios/pull/210#issuecomment-598991188 #214, I’d assume it hasn’t been fixed.

**Comment by MaYanpeng** [comment]
Deadlock due to multithreaded call to OpeGL interface.

**Comment by fabian-guerra** [comment]
Closed in favor of https://github.com/mapbox/mapbox-gl-native/issues/16530
