### ISSUE TITLE
Change specific street colour  

### ISSUE THREAD

**Issue by hiteshborse12** [mapbox/mapbox-gl-native-ios#277]
I have an iOS app with a map where the user can see roads of different colors with a specific meaning.
`
For example - Show some roads red which has a particular meaning and some roads green which has a different meaning etc. so that the user will see the map with color-coded roads.
`
All I have is the name of the road and the color which has to be assigned to the road from the API.

Is it possible to achieve this using your map? Any suggestions would really be appreciated. Thanks

**Comment by captainbarbosa** [comment]
Hi @hiteshborse12  — thanks for using Mapbox. This GitHub repository is only intended to track the development the Mapbox Maps SDK for iOS. 

For help with “how do I” questions, we recommend first checking out our [examples](https://docs.mapbox.com/ios/maps/examples/) and [API reference](https://docs.mapbox.com/ios/api/). If you still have questions after that, we recommend reaching out to others on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or to our excellent [mobile support team](https://www.mapbox.com/contact/support/).
