### ISSUE TITLE
Runtime styling snapshotter tests fail intermittently on CI

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-native-ios#291]
`-[MGLMapSnapshotterTests testRuntimeStyling]` has failed intermittently on CI ever since https://github.com/mapbox/mapbox-gl-native-ios/pull/189#issuecomment-618785454. I refactored a helper method to add another snapshotter test that was ultimately disabled; not sure why it causes this test to become unreliable though.

/cc @mapbox/maps-ios

**Comment by fabian-guerra** [comment]
The current tests draws:
`expectedImage` as 
![expectedImage](https://user-images.githubusercontent.com/2745166/80753170-6d60ca80-8af2-11ea-810b-8ad1e036896a.png)

`actualImage_1` as an image with clear color
![actualImage_1](https://user-images.githubusercontent.com/2745166/80753201-7c477d00-8af2-11ea-8d02-2f24454ceb67.png)

/cc @1ec5

**Comment by 1ec5** [comment]
I think the culprit is the changes in #189 to test #280. Instead of unconditionally looking at Null Island, the snapshotter is configured to snapshot whatever the style specifies as its default camera. But even in the runs that fail, the style finishes loading, the map transform finishes transitioning to the default camera, and `mbgl::Map::Impl::onDidFinishRenderingMap()` gets called (which would result in `-[MGLMapViewDelegate mapViewDidFinishLoadingMap:]` getting called in a map context).

**Comment by 1ec5** [comment]
#293 works around the issue for now, since it’s frequently blocking builds. mapbox/mapbox-gl-native#16454 tracks the likely issue upstream in mbgl.

**Comment by captainbarbosa** [comment]
This [might be happening again](https://github.com/mapbox/mapbox-gl-native-ios/issues/401)...?
