### ISSUE TITLE
MGLShapeSource features(matching: NSPredicate) returns old data

### ISSUE THREAD

**Issue by akovalov** [mapbox/mapbox-gl-native-ios#301]
### Steps to reproduce

 1. Update existing MGLShapeSource every minute with a new shape like the following
```
...
var shapeSource: MGLShapeSource?
...
shapeSource?.shape = shapeFromGeoJson
mapView?.style.addSource(shapeSource!)
```
 2. Get feature from the source
```
let feature = shapeSource?.features(matching: NSPredicate(format: "uuid == %@", uuid))
```
### Expected behavior

`feature` will contain the latest data from just added source

### Actual behavior

`feature` contains the previously added source data 
But if add delay it works correctly
```
DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
    let feature = self.shapeSource?.features(matching: NSPredicate(format: "uuid == %@", uuid))
}
```
I assume there is some delay in rendering new shape data on layer (like ~0.5s) and it could differ based on features count and layer drawing complexity.

It would be good to understand what caused this delay and how to deal with it - get a callback/delegate or a property like loaded etc. Please advice.

### Configuration

**Mapbox SDK versions: Mapbox-iOS-SDK (5.8.0)** 
**iOS/macOS versions: iOS 13.4.1** 
**Device/simulator models: iPad Pro (9.7 inch) Simulator**
**Xcode version: 11.4.1**

**Comment by 1ec5** [comment]
> get a callback/delegate or a property like loaded etc.

Yes, a callback on tile load would be awesome (even more awesome if it came with a way to manipulate what has been loaded). mapbox/mapbox-gl-native#2775 tracks the various ways in which MGLMapViewDelegate doesn’t align with MKMapViewDelegate.

Fortunately, you may be able to wait for the map’s next render cycle by implementing either `-mapViewDidFinishRenderingFrame:` or the undocumented `-mapViewDidFinishRenderingMap:fullyRendered:`. (The `fullyRendered:` flag isn’t fully implemented; that’s mapbox/mapbox-gl-native#1804.)
