### ISSUE TITLE
[Documentation or Enhancement] Way to change the FOV of the camera

### ISSUE THREAD

**Issue by fifiDesPlaines** [mapbox/mapbox-gl-native-ios#304]
Hi there,

I noticed it was possible to change the FOV of the camera in Mapbox GL JS.
I didn't see this property in the doc files. Is there a way to change the FOV of the camera ?

**Mapbox SDK versions:** 5.9

**Comment by captainbarbosa** [comment]
@fifiDesPlaines, do you have an example of what behavior you've seen in Mapbox GL JS? 

I think you might be looking for the ability to change the pitch and rotation of the map camera - you can do this by changing the values on the [`MGLMapCamera`](https://docs.mapbox.com/ios/api/maps/5.9.0/Classes/MGLMapCamera.html) object or by using any of these [other camera manipulation APIs](https://docs.mapbox.com/ios/api/maps/5.9.0/Classes/MGLMapView.html#/Manipulating%20the%20Viewpoint).

[Here's an example for iOS, for reference](https://docs.mapbox.com/ios/maps/examples/camera-animation/).

**Comment by fifiDesPlaines** [comment]
I would like to change the perspective of the camera. My aim is to get an isometric view of the map. The syntax with Mapbox GL JS is `map.transform._fov = valueOfThePerspective`.

I didn't find any official documentation talking about this parameters... just this github post about this topic : https://github.com/mapbox/mapbox-gl-js/pull/3790
