### ISSUE TITLE
No showsUserLocation in macOS

### ISSUE THREAD

**Issue by gazsiazasz** [mapbox/mapbox-gl-native-ios#310]
I tried to set the `showsUserLocation` to true in the macOS SDK, but unfortunately it is not present there.
The Apple Maps has the ability to display my location, so technically it is possible.

### Steps to reproduce

 1. Instantiate a `MGLMapView`.
 2. Set the `showsUserLocation` property to `true`.

### Expected behavior

The map shows my location on the map.

### Actual behaviour

Not able to build the project if there is a reference to `showsUserLocation`.

### Configuration

**Mapbox SDK versions:** 
0.16.0
**iOS/macOS versions:** 
10.15.4 (19E287)
**Device/simulator models:**
**Xcode version:** 
11.5 (11E608c)

**Comment by captainbarbosa** [comment]
@gazsiazasz `showsUserLocation` is only available for the iOS Maps SDK.

The related issue can be found here: https://github.com/mapbox/mapbox-gl-native/issues/4983

We are unable to work on this particular feature at the moment, but if you'd like to contribute we would be happy to review any third party contributions.
