### ISSUE TITLE
Update MGLLocationManager to iOS 14

### ISSUE THREAD

**Issue by fabian-guerra** [mapbox/mapbox-gl-native-ios#337]
MGLLocationManager has to update the location authorization API to reflect [iOS 14](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600215-accuracyauthorization?changes=latest_minor) changes. 

The main changes are:
- [x] Add `accuracyAuthorization` property.
- [x] Add the equivalent of `func requestTemporaryFullAccuracyAuthorization(withPurposeKey: String)` to `MGLLocationManager`
- [x] Change from class to instance the method `authorizationStatus()` 
~~- [ ] Modify `MGLMapView` to request the accuracy authorization~~
- [x] Update `MGLLocationManager` documentation to account the state management involving `accuracyAuthorization`

**Comment by knov** [comment]
Follow up for visual indicator in https://github.com/mapbox/mapbox-gl-native-ios/issues/372
