### ISSUE TITLE
MGLNetworkConfiguration#errorLog drops error details

### ISSUE THREAD

**Issue by reidab** [mapbox/mapbox-gl-native-ios#347]
Nearly a PR, but I don't have time to get the build running locally at the moment.

> We've been seeing errors logged from `[MGLNetworkConfiguration errorLog:]` with incomplete messages that look like `Requesting: (null) failed with error: <MGLNetworkConfiguration: 0x60000291ea60>`.
> 
> Why is the URL `(null)`? Why is the error an instance of `MGLNetworkConfiguration`?

This is a companion issue to https://github.com/mapbox/mapbox-gl-native/issues/16511, which covers the first part of the problem. Until that's fixed, fixing this won't do anything because the details will be dropped upstream.

The implementation of MGLNetworkConfiguration takes a format string and variadic arguments, but it doesn't pass the variadic args along when calling `MGLLogError`:

https://github.com/mapbox/mapbox-gl-native-ios/blob/171ff9484a48c39151a4bb793911889996f54156/platform/darwin/src/MGLNetworkConfiguration.m#L134-L136

**Comment by julianrex** [comment]
This will be fixed by the next release.
