### ISSUE TITLE
Can't download 6.0 with provided downloads token

### ISSUE THREAD

**Issue by dimazen** [mapbox/mapbox-gl-native-ios#354]
### Steps to reproduce

 1. Create a Download token
 2. Try to install a 6.0 version via CocoaPods

### Expected behavior
SDK installs correctly

### Actual behavior
I'm always getting a 401 no matter how many tokens I have tried with a correct scope `Downloads:Read`. Even was trying to swap a user name in the `.netrc` file to a my username, but no luck. Tried out to name `netrc` or `.netrc` and the result is the same - 401.

### Configuration

**Mapbox SDK versions:** 6.0
**iOS/macOS versions:** N/A
**Device/simulator models:** N/A
**Xcode version:** N/A

You can check it out by running a following curl (the same that CocoaPods runs, so I just copy and pasted it):
```
curl -f -L -o sdk.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.0.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional
```

Make sure, that you have a .netrc file in the running directory with a following format:
```
machine api.mapbox.com 
login mapbox
password <here is my secret token for downloads>
```

p.s. I ensured that token has a download scope (and only), checked guide one more time.

**Comment by captainbarbosa** [comment]
Hi @dimazen - I was able to download this without issue using my credentials. We should probably double check your Mapbox account, but move the discussion elsewhere outside of a public project for your security. Can you please reach out to our support team using [this form](https://www.mapbox.com/contact/) so we can continue this discussion? In your message, please provide a link to this ticket, your Mapbox username, and the version of CocoaPods you're using. Thanks!

**Comment by dimazen** [comment]
Done! Looking forward for help :)

Thanks for the response!

**Comment by dimazen** [comment]
@captainbarbosa my bad: was trying to use a local .netrc file, while curl was expecting it to be in the root of the user. 

For the local machine this is ok, however, when it comes to the CI, it's gonna be a huge pain, since there is no way to specify a .netrc per repo, but rather you have to set it per user which usually shares a lot of projects with a different netrc that can be used.

**Comment by heyehao2008** [comment]
the .netrc file path is ~/.netrc. not in your project root directory. check this!

**Comment by knov** [comment]
@dimazen please try this solution

Create a downloads:read token on mapbox.com for use on CircleCI.


Add an SDK_REGISTRY_TOKEN environment variable to your CI system of choice.


In your CI config file, insert a new run step before fetching dependencies to the build job which does :
echo "machine api.mapbox.com
login mapbox
password ${SDK_REGISTRY_TOKEN}" >
~/.netrc

**Comment by dimazen** [comment]
Hello, @knov! I've managed to handle this on the GitLab CI by adding a following script in conjunction with a new env vars:
```
  - 'echo -e "machine $NETRC_MAPBOX_MACHINE\nlogin $NETRC_MAPBOX_LOGIN\npassword $NETRC_MAPBOX_PASSWORD" > ~/.netrc'
```

That's part of the .gitlab-ci.yml.

@heyehao2008 Yep, I've already figured that out. Huge thanks for help!
