### ISSUE TITLE
Route exceeds maximum distance limitation

### ISSUE THREAD

**Issue by sohail-niazi** [mapbox/mapbox-gl-native-ios#369]
HI, I am using Mapbox sdk for map and directions. I getting the error:

"Route exceeds maximum distance limitation"

on route generation if I add multiple stops on Map. 
Can you please clarify what is maximum distance limit for directions. Thanks.

**Comment by captainbarbosa** [comment]
If you're using MapboxDirections.swift (either by itself or using the Mapbox Navigation SDK for iOS), note that there is a three waypoint limit* when requesting directions with the `.automobileAvoidingTraffic` profile identifier.

\* Source: [Mapbox Directions for Swift](https://github.com/mapbox/mapbox-directions-swift/blob/c91d3ba051fa67759b905299dad85a163697efcf/Sources/MapboxDirections/RouteOptions.swift#L14) documentation and [Mapbox Direction API documentation](https://docs.mapbox.com/ios/navigation/overview/route-generation/#include-multiple-stops).

Please note, this repository is for reporting bugs associated with the Mapbox Maps SDK for iOS. If you have additional questions about using maps and navigation inside your app, please reach out to our [support team](https://www.mapbox.com/contact/).
