### ISSUE TITLE
clustering not working with MGLPointCollectionFeature

### ISSUE THREAD

**Issue by kostiag** [mapbox/mapbox-gl-native-ios#378]
**Mapbox Navigation SDK version:**
6.0

I have attempted to reach out to support as well as try to get help through [stackoverflow](https://stackoverflow.com/questions/63005682/clustering-mglannotations-images-on-ios-mapbox-using-mglpointcollectionfeature)

I have tried updating/removing and reading layers, but that did not help. self.clusterSource.shape is updated based on user actions (selection on what to display on the map) Individual icons appear correctly, but can't get clustering to work and at this point I am not sure if it is something that I am not doing correctly or something else.
Would love to provide any details that would be helpful.

**Comment by 1ec5** [comment]
Hi, does [this answer](https://stackoverflow.com/a/63345865) address the problem you were running into?

If I’m not mistaken, this issue is specific to the iOS map SDK and doesn’t involve the iOS navigation SDK, so I’ve transferred it to the appropriate repository for visibility.

**Comment by kostiag** [comment]
yes this resolved my issue,
thanks

**Comment by 1ec5** [comment]
Great to hear!
