### ISSUE TITLE
[iOS] Update MapboxMobileEvents to 0.10.3 to make Mapbox-iOS-SDK buildable in app extensions

### ISSUE THREAD

**Issue by behdaad** [mapbox/mapbox-gl-native-ios#424]
When using Mapbox iOS SDK 5.6.0 or newer, App Extensions have a build error related to usage of `UIApplication.sharedApplication` which is because of the inclusion of `MapboxMobileEvents` pod. This issue is resolved in the latest version of MapboxMobileEvents (0.10.3), but currently Mapbox-iOS-SDK uses versuin 0.10.2.

### Steps to reproduce

 1. Create an App Extension, such as a NotificationContentExtension
 2. Add Mapbox-iOS-SDK 5.6.0 to both the app and extension
 3. `pod install`
 4. Build the project

### Expected behavior
The project builds successfully. 

### Actual behavior
Project build fails with this error:
```
.../Pods/MapboxMobileEvents/MapboxMobileEvents/MMEUINavigation.m:6:73: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```
Mentioned error is for version 6.2.0-beta.1, and may be on a different line on other versions. 

### Configuration

**Mapbox SDK versions:** from Mapbox-iOS-SDK 5.6.0 to Mapbox-iOS-SDK 6.2.0-beta.1
**iOS/macOS versions:** N/A
**Device/simulator models:** N/A
**Xcode version:**  Xcode 11.7

**Comment by julianrex** [comment]
Thanks @behdaad, see also:

- https://github.com/mapbox/mapbox-gl-native-ios/pull/415#issuecomment-686803965
- https://github.com/mapbox/mapbox-events-ios/issues/236

**Comment by julianrex** [comment]
This is fixed by https://github.com/mapbox/mapbox-gl-native-ios/pull/431
