### ISSUE TITLE
v6.2.0-beta.2 cherry picks

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#433]
Cherry pick the following PRs to `release-z`:

- [x] https://github.com/mapbox/mapbox-gl-native-ios/pull/420 - b9a1d7668050a56d19624c22a0b68457b3d09fdb
- [x] https://github.com/mapbox/mapbox-gl-native-ios/pull/427 - 70a26e8490b4701c8eddcaac9fcb60b4c91337a8
- [x] https://github.com/mapbox/mapbox-gl-native-ios/pull/429 - a2cbab0bfb3ca1982c79883ef8a949640f0cc3e9
- [x] https://github.com/mapbox/mapbox-gl-native-ios/pull/431 - c4944b687ef479ccaa4be6308c7bda98ac0da232 
- [x] https://github.com/mapbox/mapbox-gl-native-ios/pull/432 - waiting to land
- [x] Update to gl-native 5.0.0

**Comment by fabian-guerra** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-native-ios/pull/437
