### ISSUE TITLE
Building framework now using mapbox-ios-sdk-gl-core-static instead of my custom mapbox-gl-native

### ISSUE THREAD

**Issue by nnhubbard** [mapbox/mapbox-gl-native-ios#434]
I have made modifications to `mapbox-gl-native` and when building the `native-ios` framework it previously built using my changes to `mapbox-gl-native`. Now, after updating `mapbox-gl-native-ios` with the latest commits, it seems to be using  `mapbox-ios-sdk-gl-core-static` that it is downloading from `https://api.mapbox.com/downloads/v2/carthage/mobile-maps-gl-core/mapbox-ios-sdk-gl-core-static.json` and ignoring my custom changes in the vender folder for `mapbox-gl-native`. Why is this?

### Steps to reproduce

 1. Update to latest `mapbox-gl-native-ios`
 2. Run `make iframework BUILDTYPE=Release`

### Expected behavior

A `Mapbox.framework` file would be generate using my `vendor/mapbox-gl-native` which I have customized.

### Actual behavior

It seems to no longer use `vendor/mapbox-gl-native` and use a static library downloaded instead. How can I get back to using my own changes that I have made in `vendor/mapbox-gl-native`?

### Configuration

**Mapbox SDK versions:** 
**iOS/macOS versions:** iOS 14
**Device/simulator models:** iPhone 11 Pro
**Xcode version:** 12, beta 6

**Comment by knov** [comment]
@nnhubbard, Please see the [note about v6.0.0](https://github.com/mapbox/mapbox-gl-native-ios/issues/340) releases as it pertains to GL Native consumption and licensing.
