### ISSUE TITLE
build from source for macOS

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-native-ios#444]
### Steps to reproduce

 1. Checkout latest from master
 2. make xpackage

### Expected behavior

Sucessfully build for macOS

### Actual behavior

```
make: *** No rule to make target `vendor/mapbox-gl-native/CMakeLists.txt', needed by `build/macos/Mapbox GL Native.xcodeproj'.  Stop.
```

### Configuration

**Mapbox SDK versions:** master as of b39c4856cca8f938a4c311cef246613b1af78b0f
**iOS/macOS versions:** macOS 10.15.6
**Device/simulator models:**
**Xcode version:**  11.7

**Comment by 1ec5** [comment]
#326 changed the build system for this repository to depend on a binary of mbgl that is published only on mapbox.com, so while it’s possible to build the platform-specific SDK code from source, the build system is no longer compatible with the gl-native repository built from source as is.

I haven’t gotten a chance to verify that `make xpackage` still works as designed, but if this is blocking you, I know it worked as of [v0.16.0](https://github.com/mapbox/mapbox-gl-native-ios/releases/tag/macos-v0.16.0), so you could try checking out that tag.

**Comment by halset** [comment]
@1ec5 : Thanks, that worked fine!
