### ISSUE TITLE
Version 6.2.0 introduces a bug when using setCenter

### ISSUE THREAD

**Issue by Frederikdam** [mapbox/mapbox-gl-native-ios#461]
If you use setCenter with the current zoom level and current center coordinate, meaning that the camera does not move, then the completion handler will never be called, unless you interact with the map. 

It is worth noting that this bug was introduced in version 6.2.0, since it was working as expected in 6.1.0.

### Steps to reproduce

 1. Set the map zoom level to a specific constant
 2. Set the map center coordinate to a specific constant
 3. Use setCenter with those specific constants and see that the completion handler is not called.

### Expected behavior

The completion handler is always called after using setCenter

### Actual behavior

The completion handler is only called on setCenter if the camera is moved. If the camera does not change, the completion handler is for some odd reason first called after you interact with the map.

### Configuration

**Mapbox SDK versions:** 6.2.0
**iOS version:** 14.0
**Device:** 11 Max Pro
**Xcode version:** 12

**Comment by julianrex** [comment]
Thanks for the report, we're looking into it.

**Comment by julianrex** [comment]
Fixed in #463.

**Comment by Frederikdam** [comment]
Thanks @julianrex . When will the release-a milestone be released? I'm currently in a situation where version 6.1.0 is useless on iOS 14 because it is too laggy and version 6.2.0 is useless because the completion handlers aren't called correctly.

**Comment by julianrex** [comment]
This will be released in a 6.2.1 which is due soon.
