### ISSUE TITLE
Possibly map overscroll bug in ios14

### ISSUE THREAD

**Issue by swsong12** [mapbox/mapbox-gl-native-ios#462]
### Steps to reproduce

 1. Load map

### Expected behavior

Overscroll disabled.

### Actual behavior

Overscroll enabled. Before, we didn't have any empty spaces like the screenshot below. We haven't had this problem before with iOS 14 Beta. 
![IMG_8879](https://user-images.githubusercontent.com/22624800/93582494-856fb280-f9dd-11ea-9215-4eb952a6a873.jpg)

### Configuration

**Mapbox SDK versions: 6.2.0-beta2** 
**iOS/macOS versions: ios 14 (official)** 
**Device/simulator models: iPhone 11 pro, iPhone XR, iPhone XS Max**
**Xcode version: Xcode 12 GM**

**Comment by julianrex** [comment]
This should be fixed in 6.2.0. Can you please retest.

**Comment by swsong12** [comment]
Fixed in 6.2.0 Thanks! 👍
