### ISSUE TITLE
Annotations are not staying fixed on the specified coordinate

### ISSUE THREAD

**Issue by Frederikdam** [mapbox/mapbox-gl-native-ios#480]
A bug was introduced in version 6.2.0, which makes annotations not staying fixed in place when panning the map. Seems like the annotation is staying fixed while the user is panning, but the moment you release and the map starts to decelerate in the direction you panned, the annotation starts to move.
### Steps to reproduce

 1. Place an annotation on the map
 2. Swipe/Pan the map
 3. Observe that the placed annotation is not staying fixed while the map starts to decelerate

### Expected behavior
The annotation stays fixed throughout the map panning gesture

### Actual behavior
The annotation is moving out of place when the map starts to decelerate from a pan gesture

### Configuration

**Mapbox SDK version:** 6.2.1
**iOS version:** 14
**Device:** iPhone 11 Max Pro
**Xcode version:** 12.0

**Comment by swsong12** [comment]
same issue here! was fine before 6.2.0

**Comment by julianrex** [comment]
Thanks for the report - we've reproduced and are looking at solutions.
