### ISSUE TITLE
MGLSymbolStyleLayer not being loaded initially in version 6.2.1

### ISSUE THREAD

**Issue by Frederikdam** [mapbox/mapbox-gl-native-ios#484]
This bug is a bit tricky, since it only occurs on the initial load of the map. I have an application where I add a MGLSymbolStyleLayer and a MGLHeatmapStyleLayer on "mapViewDidFinishRendering" that shows some data on the map, which is working in version 6.1.0. Since version 6.2.0, I am experiencing that if I do a fresh install of my application, the MGLSymbolStyleLayer is simply not loading/showing, until I kill and restart the app. The MGLHeatmapStyleLayer is working as expected and is showing on the initial launch. Somehow MGLSymbolStyleLayer is not being added correctly on the initial launch of the application. Maybe Mapbox is caching some configurations that makes it work on repeated launches?

It is worth noting that I tested my exact codebase with version 6.1.0 and it seems to work. Upgrading to version 6.2.1 introduces this bug.

### Steps to reproduce

 1. Fresh install of the app
 2. On "mapViewDidFinishRendering" add symbol layer

### Expected behavior

On the initial launch of the application I will see all of the symbol layers I added to the map after the map finished rendering

### Actual behavior

On the initial launch, symbol layers are not loaded correctly. Repeated launches works as expected, but not the initial one.

### Configuration

**Mapbox SDK version:** 6.2.1
**iOS version:** 14.0
**Device model:** iPhone 11 Pro Max
**Xcode version:** 12.0

**Comment by julianrex** [comment]
@Frederikdam are you able to provide a sample that we test against?

**Comment by julianrex** [comment]
Also, did you try `6.2.0`?

**Comment by captainbarbosa** [comment]
@Frederikdam I just tried reproducing this in our example app, but I was unable to do so while running v6.2.1 on an iPhone 11 Pro (physical device, not sim).

For reference, [here is the setup](https://github.com/mapbox/ios-sdk-examples/blob/25c26ec171a0fad23b2b81dc9eaec8bd8398273a/Examples/Swift/HeatmapExample.swift) I was using to attempt to reproduce, which exists on [this debugging branch](https://github.com/mapbox/ios-sdk-examples/compare/nb/reproduce-484) I made. Everything looks to be running as expected with this example. Can you provide additional information about how we could isolate a minimal test case?

**Comment by Frederikdam** [comment]
Hi. Thanks, I appreciate your attempt to reproduce, I was able to isolate the issue and fix it. Apparently, I was calling `MGLStyle.setImage` too early, resulting in my symbol layers not being able to fetch the correct assets to display.
