### ISSUE TITLE
Call to setCamera on MGLMapView is causing too many layoutSubviews updates on iOS 14.

### ISSUE THREAD

**Issue by MaximAlien** [mapbox/mapbox-gl-native-ios#500]
Starting from `iOS 14` calls to animated camera changes using `MGLMapView.setCamera(_:withDuration:animationTimingFunction:)` and similar methods cause too many `layoutSubviews` updates. Such behavior cannot be reproduced on `iOS 13` and earlier. It's also not possible to reproduce behavior on `iOS 14` when setting camera without animation when using `setCamera(_:animated:)`.

### Steps to reproduce

Consider such code:

```swift
import UIKit
import Mapbox

class ViewController: UIViewController {
    
    var mapView: MGLMapView?
    var timer: Timer?
    let tag = "[Camera test]"
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        testCamera()
    }
    
    func testCamera() {
        mapView = MGLMapView(frame: view.bounds)
        mapView?.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        mapView?.userTrackingMode = .follow
        mapView?.style?.transition = MGLTransition(duration: 1.0, delay: 1.0)
        mapView?.zoomLevel = 15.0
        
        view.addSubview(mapView!)
        
        timer = Timer.scheduledTimer(withTimeInterval: 5.0, repeats: true) { timer in
            if let centerCoordinate = self.mapView?.centerCoordinate {
                let camera = MGLMapCamera(lookingAtCenter: centerCoordinate,
                                          altitude: CLLocationDistance(Int.random(in: 0...1000)),
                                          pitch: CGFloat(Int.random(in: 0...45)),
                                          heading: CLLocationDirection(Int.random(in: 0...360)))
                let animationTimingFunction = CAMediaTimingFunction(name: .linear)
                NSLog("\(self.tag) Started animation.")
                self.mapView?.setCamera(camera, withDuration: 3.0, animationTimingFunction: animationTimingFunction, completionHandler: {
                    NSLog("\(self.tag) Finished animation.")
                })
            }
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        NSLog("\(tag) \(#function)")
    }
}
```

After running this code on `iOS 14` `UIViewController.viewDidLayoutSubviews` will be called too many times within really short period of time. For example: 
```
2020-10-07 09:53:52.263605-0700 MapboxCocoaPodsTest[4665:95349] [Camera test] Started animation.
2020-10-07 09:53:52.295483-0700 MapboxCocoaPodsTest[4665:95349] [Camera test] viewDidLayoutSubviews()
... 96 more times
2020-10-07 09:53:55.283449-0700 MapboxCocoaPodsTest[4665:95349] [Camera test] viewDidLayoutSubviews()
2020-10-07 09:53:55.283719-0700 MapboxCocoaPodsTest[4665:95349] [Camera test] Finished animation.
```

### Expected behavior

Since client apps might override either `UIViewController.viewDidLayoutSubviews` or `UIView.layoutSubviews` and run additional UI tasks there it might cause UI lags. This issue causes issues described in Navigation iOS SDK [here](https://github.com/mapbox/mapbox-navigation-ios/issues/2671) and [here](https://github.com/mapbox/mapbox-navigation-ios/issues/2658).

### Actual behavior

`UIViewController.viewDidLayoutSubviews` or `UIView.layoutSubviews` is called too often when setting camera on `iOS 14`.

### Configuration

**Mapbox SDK versions:** `6.2.1`
**iOS/macOS versions:**  `iOS 14.0`
**Device/simulator models:** `iPhone 11 iOS Simulator`
**Xcode version:** `Xcode 12.0`

**Comment by julianrex** [comment]
Turns out both the compass and scalebar ornaments are triggering layoutSubviews. See #501 for a fix for the compass.

For the scalebar, this is due to auto layout and the use of intrinsicContentSize.
