### ISSUE TITLE
Can't use Mapbox with Cocoapods and Xcode 12

### ISSUE THREAD

**Issue by aodhol** [mapbox/mapbox-gl-native-ios#503]
### Steps to reproduce

 1. Create a new project.
 2. Create a Podfile and add mapbox: `pod 'Mapbox-iOS-SDK', '~> 6.2.1'`
 3. Install the pods and attempt to run.

### Expected behavior

To be able to simply run.

### Actual behavior

`framework not found MapboxMobileEvents`

### Configuration

**Mapbox SDK versions:** 6.2.1
**iOS/macOS versions:** 14.0
**Device/simulator models:** iPhone Xs
**Xcode version:** 12.0.1

Things that did not work:

- Updating to pre-rel cocoapods.
- Excluding arm64 arch.
- Building to device.
- Using 6.3.0 alpha.
- Clearing derived data.
- Ensuring arm64 was excluded in via post install in the podfile.

**Comment by captainbarbosa** [comment]
@aodhol Which version of CocoaPods were you originally attempting on? Also, could you please post your `podfile` here if possible? You may need to preface your `pod install` command with `pod repo update` as well.

**Comment by aodhol** [comment]
@captainbarbosa I tried with `1.10.0.rc.1` and `1.9.3` I also updated the repo.. I've tried the pre-release version of MapBox and 6.2.1.

```
PODS:
  - Mapbox-iOS-SDK (6.2.1):
    - MapboxMobileEvents (~> 0.10.4)
  - MapboxAccounts (2.3.0)
  - MapboxCommon (4.0.1)
  - MapboxCoreNavigation (1.0.0):
    - MapboxAccounts (~> 2.3.0)
    - MapboxDirections (~> 1.0)
    - MapboxMobileEvents (~> 0.10.2)
    - MapboxNavigationNative (~> 18.0.5)
    - Turf (~> 1.0)
  - MapboxDirections (1.0.0):
    - Polyline (~> 4.2)
    - Turf (~> 1.0)
  - MapboxMobileEvents (0.10.5)
  - MapboxNavigation (1.0.0):
    - Mapbox-iOS-SDK (~> 6.0)
    - MapboxCoreNavigation (= 1.0.0)
    - MapboxMobileEvents (~> 0.10.2)
    - MapboxSpeech (~> 1.0)
    - Solar (~> 2.1)
  - MapboxNavigationNative (18.0.5):
    - MapboxCommon (= 4.0.1)
  - MapboxSpeech (1.0.0)
  - MapboxStatic.swift (0.11.0):
    - Polyline (~> 4.2)
  - Polyline (4.2.1)
  - Solar (2.1.0)
  - Turf (1.0.0)

DEPENDENCIES:
  - Mapbox-iOS-SDK
  - MapboxNavigation
  - MapboxStatic.swift

SPEC REPOS:
  trunk:
    - Mapbox-iOS-SDK
    - MapboxAccounts
    - MapboxCommon
    - MapboxCoreNavigation
    - MapboxDirections
    - MapboxMobileEvents
    - MapboxNavigation
    - MapboxNavigationNative
    - MapboxSpeech
    - MapboxStatic.swift
    - Polyline
    - Solar
    - Turf

SPEC CHECKSUMS:
  Mapbox-iOS-SDK: c5a2ec3a3a0a77ee0ba78f91380e83898cb6aa41
  MapboxAccounts: 84abfdde95d9dc483f604c1b0fe1861edf691ce7
  MapboxCommon: 50fb1be5136cb30f123b7e2fbe4b2ea2e86f2216
  MapboxCoreNavigation: 04d44485e8da4d5ded816dcd7e419edabf71cbb7
  MapboxDirections: 35c071db30397f06708ae305287f10395586e154
  MapboxMobileEvents: 7f6fb7fb0360302f524d198d36ccec3a0beae523
  MapboxNavigation: 699145d57aa95ebfe14e5de34d45b133d0c46e5d
  MapboxNavigationNative: d2b70c1d60a10aeb25c3b3c483b59332b4773a03
  MapboxSpeech: 4b3aea42e35d056fae1d7ad847a9fc0f412d911e
  MapboxStatic.swift: 3a39f0b077a7fb0568fd53f27a76c402b07ef408
  Polyline: 0e9890790292741c8186201a536b6bb6a78d02dd
  Solar: 2dc6e7cc39186cb0c8228fa08df76fb50c7d8f24
  Turf: 29b37f6d67f184a7b2d00f594c3e20b3e5474b7d

PODFILE CHECKSUM: c8dc910dffb05eb747879116c3140c882197c29b

COCOAPODS: 1.10.0.rc.1
```

**Comment by ZiZasaurus** [comment]
Hi @aodhol, I am unable to reproduce this behavior with a new Xcode project. Can you confirm the Xcode version that you are using in terminal using `xcodebuild -version`? Additionally, have you run `pod update` as well as `pod init`?

**Comment by aodhol** [comment]
@ZiZasaurus `Xcode 12.0.1 Build version 12A7300`

**Comment by sdamaraju** [comment]
"Additionally, have you run pod repo update before running pod install?"
-This helped me
