### ISSUE TITLE
The latest versions of Mapbox not published for CocoaPods

### ISSUE THREAD

**Issue by zo0m** [mapbox/mapbox-gl-native-ios#530]
The latest versions of Mapbox (from 5.9.0) were not published to api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages

e.g. check *.podspec of 6.2.1:
https://github.com/CocoaPods/Specs/blob/master/Specs/a/5/9/Mapbox-iOS-SDK/6.2.1/Mapbox-iOS-SDK.podspec.json

source URL:
[https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.2.1/mapbox-ios-sdk-dynamic.zip](https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.2.1/mapbox-ios-sdk-dynamic.zip)

response:
`{"message":"Not Authorized - No Token"}`

**Comment by behdaad** [comment]
As of version `6.0.0`, you need to provide a token to be able to download Mapbox SDK. More info here: https://docs.mapbox.com/ios/maps/overview/#install-the-maps-sdk

**Comment by zo0m** [comment]
Thank you!

`.netrc` file  solved my problem
