### ISSUE TITLE
[Bitrise CI] Pulling cocoapod for v6.3.0 even when adding .netc fails

### ISSUE THREAD

**Issue by kcw-grunt** [mapbox/mapbox-gl-native-ios#559]
### Question
Assumed users of Mapbox Maps SDK have experienced this issue already and hoped they are aware of a workaround?

### Steps to reproduce

 1. Add .netrc to the repo and commit per [Configure your secret token](https://docs.mapbox.com/ios/maps/overview/#install-the-maps-sdk), push to the remote
 2. Bitrise trips trigger to run build
 3. Build fails per _404 Unauthorized Access_

### Expected behavior

 1. Add .netrc to the repo and commit per [Configure your secret token](https://docs.mapbox.com/ios/maps/overview/#install-the-maps-sdk), push to the remote
 2. Bitrise trips trigger to run build
 3. Build runs cocoapod's  `pod install`
 4. Mapbox SDK v6.3.2 is downloaded and installed.
 
### Configuration

**Mapbox SDK versions: v6.3.2** 
**iOS/macOS versions: iOS 14** 
**Device/simulator models: iPhone 11**
**Xcode version: 12** 

### Other Information

This happens successfully locally.

#### Bitrise Header
```
Agent version:	1.15.1
Hostname:	prd-veg-std-g-xcode-12-1-XXXXXXXj9.local
Start time:	2020-11-24T11:51:13Z
$ bitrise "run" "--config" "/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise-agent371570519/bitrise.yml" "--inventory" "/var/folders/6q/wgy6jtp12w5gzgm9XXXXXw0000gn/T/bitrise-agent371570519/bitrise.secrets.yml" "--json-params-base64" "eyXXXXcnkifQ=="
```

#### Cocopods Install Log gist

```
-> Installing Mapbox-iOS-SDK (6.3.0)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20201124-1696-1xp4piw/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   curl: (22) The requested URL returned error: 401 Unauthorized
[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20201124-1696-1xp4piw/file.zip https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/downloader.rb:139:in `execute_command'
```

**Comment by kcw-grunt** [comment]
From: @misterkerry
cc: @julianrex , @ZiZasaurus

**Comment by 1ec5** [comment]
v6.3.2 hasn’t been released yet. Did you intend to install v6.2.2 or v6.3.0?

**Comment by kcw-grunt** [comment]
Hey Minh!
Yep my bad (fixed). 
I suppose the workaround is to manually add the SDK and store it in the repo.  But, I was hoping if you folks were aware of a way so Bitrise container/Xcode server does not fail to access Mapbox.

**Comment by RustamG** [comment]
@kcw-grunt 
.netrc file should be in your Home directory as it's written on the page you mentioned:
![image](https://user-images.githubusercontent.com/8288211/100363216-dcb18500-3015-11eb-9564-7d4abc2a3494.png)

Bitrise has a special step to handle this. https://www.bitrise.io/integrations/steps/authenticate-host-with-netrc

**Comment by kcw-grunt** [comment]
Mmm...that link is golden @RustamG .  Many thanks!

**Comment by kcw-grunt** [comment]
Confirmed.
