### ISSUE TITLE
CJK Glyph rasterization disabled by default in 6.3 release

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-native-ios#589]
PR https://github.com/mapbox/mapbox-gl-native-ios/pull/517 introduced support for the new "Glyphs Rasterization Mode", but it changed the default from the previously-implied "only rasterize ideographs locally" to "don't rasterize any glyphs locally".

https://github.com/mapbox/mapbox-gl-native-ios/pull/517/files#r512168040

There is code that logs a message saying it will fallback to the "ideographs rasterized locally" mode, but then it actually sets the "no glyphs" mode.

```
case MGLGlyphsRasterizationModeNone:
    MGLLogWarning(@"Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified.")
    options.rasterizationMode = mbgl::GlyphsRasterizationMode::NoGlyphsRasterizedLocally;
```

There's some discussion of this issue on the PR (https://github.com/mapbox/mapbox-gl-native-ios/pull/517/files#r512168040) but it seemed to go forward -- I'm not sure if I'm missing some context.

A customer noticed this regression in the Nav SDK for the lucky (?) reason that one of our server-side fonts was broken -- but the real issue here is that turning off local fonts is a huge performance regression for Japanese customers.

@OttyLab @1ec5 @lloydsheng @alexshalamov @jmkiley

**Comment by ChrisLoer** [comment]
Any updates on triage here? It'd be nice to get a fix into a patch release -- as is we risk hitting existing customers with a perf regression when they upgrade SDK versions (eroding trust), and potential new customers in Japan will be almost sure to run into it.

**Comment by mrousavy** [comment]
@ChrisLoer did you find a workaround for this issue?

**Comment by ChrisLoer** [comment]
@mrousavy The workaround is to just explicitly set `MGLIdeographsRasterizedLocally` -- the local glyph rasterization still works, it just got turned off by default.

**Comment by ferdicus** [comment]
> Any updates on triage here? It'd be nice to get a fix into a patch release -- as is we risk hitting existing customers with a perf regression when they upgrade SDK versions (eroding trust), and potential new customers in Japan will be almost sure to run into it.

I don't think anything meaningful is going to happen in this repo anymore, as mapbox seems to have moved all their effort to the v10 SDKs

**Comment by knov** [comment]
Please set `MGLIdeographsRasterizedLocally` explicitly. Introducing this as the default introduced a regression from the previous product functionality which could not be resolved with this default value.
