### ISSUE TITLE
Getting -180,180 as coordinates for MGLUserLocation when device denies location permissions

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-gl-native-ios#596]
### Steps to reproduce

 1. Deny location permissions on device
 2. Print out MGLUserLocation properties

### Expected behavior
Per https://docs.mapbox.com/archive/ios/maps/api/4.1.1/Classes/MGLUserLocation.html#/c:objc(cs)MGLUserLocation(py)location, we should get `nil`.

### Actual behavior
Coordinates are -180,180.

**Comment by ZiZasaurus** [comment]
@samfader, are you using `mapView.userLocation.coordinate` to obtain the user location? If so, I found that by using `mapView.userLocation?.location?.coordinate`, this is the property that returns `nil` if the user’s location has not yet been determined.

**Comment by samfader** [comment]
@ZiZasaurus That was it! Thank you.
