### ISSUE TITLE
IOS SDK isn't able to be downloaded from CocoaPods (403 Forbidden).

### ISSUE THREAD

**Issue by TraxxasWyls** [mapbox/mapbox-gl-native-ios#600]
### Steps to reproduce
 1. Add IOS SDK in podfile.
  ```bash 
use_frameworks!

platform :ios, '12.0'

inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'

target "AppName" do
   pod "Mapbox-iOS-SDK"
end
```
 2. Write command in terminal
 ```bash 
pod install
``` 
### Expected behavior
The latest release of Mapbox-iOS-SDK is installed.

### Actual behavior
403 Forbidden error while installing SDK.

<img width="623" alt="Снимок экрана 2021-04-12 в 23 57 08" src="https://user-images.githubusercontent.com/71444916/114463057-989dd600-9bec-11eb-9bff-87ba8020d2f9.png">

Where https://api.mapbox.com/downloads/v2/mobile-maps/releases/ios/packages/6.3.0/mapbox-ios-sdk-dynamic.zip doesn't provide expected data.

### Configuration

**Mapbox SDK versions: 6.3.0** 
**iOS/macOS versions: iOS 12.0 / macOS 11.2.3** 
**Device/simulator models:**
**Xcode version: 12.4**

**Comment by JackJBlundell** [comment]
Did you ever solve this> I am experiencing the same issue

**Comment by masein** [comment]
I'm having the same issue and whether I use SPM I can not add it too

**Comment by masein** [comment]
the problem was for the key it's fixed now
