### ISSUE TITLE
Investigate binary size increase in 5.5.0

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#63]
In 5.5.0, the binary size jumped significantly.

Here are the 5.*.0 minor releases (penultimate column is total size):

```
5.5.0	4816896	294912	0	124392	5236200	4fe5e8
5.4.0	3784704	278528	0	118200	4181432	3fcdb8
5.3.0	3735552	278528	0	117456	4131536	3f0ad0
5.2.0	3686400	278528	0	117028	4081956	3e4924
5.1.0	3637248	278528	0	116224	4032000	3d8600
5.0.0	3637248	278528	0	115548	4031324	3d835c
```

/cc @samfader @zugaldia

**Comment by julianrex** [comment]
Looking at compiler flags (picking `symbol_layer.cpp` as the example) comparing `mapbox-gl-native` (old build system) vs this repo (new build system) there are a few key differences, when building with the `Release` configuration:

| Flag | 5.5.0 | 5.4.0 |
|------|------|------|
| Optimization | `-O3` | `-Os` |
| LTO | not present | `-flto` |
| RTTI | not present | `-fno-rtti` |

@tmpsantos a few questions:
- Should we be using the new `MinSizeRel` configuration for releases? That seems to use `-Os` and `-flto`, but not `-fno-rtti`.
- Is the lack of `-fno-rtti` deliberate?
- Also `RelWithDebInfo` builds with `-O2`, is this correct?

<hr>

Here are the compiler flags, with warnings and include/framework paths excluded:
<details>
<summary>5.5.0 options</summary>
<pre>
<...>/XcodeDefault.xctoolchain/usr/bin/clang 
-x c++ 
-target armv7-apple-ios9.0 
-fmessage-length=0 
-fdiagnostics-show-note-include-stack 
-fmacro-backtrace-limit=0 
-fpascal-strings 
-O3
-DCMAKE_INTDIR=\"Release-iphoneos\" 
-DMBGL_USE_GLES2 
-DGLES_SILENCE_DEPRECATION 
-DRAPIDJSON_HAS_STDSTRING=1 
-fstrict-aliasing 
-fembed-bitcode 
-DNDEBUG 
-fPIC 
-fvisibility=hidden 
-fvisibility-inlines-hidden 
-std=c++14 
</pre>
</details>

<details>
<summary>5.4.0 options</summary>
<pre>
./build/ios/launch-c 
-x c++ 
-target armv7-apple-ios9.0 
-fmessage-length=0 
-fdiagnostics-show-note-include-stack 
-fmacro-backtrace-limit=0 
-fpascal-strings 
-Os 
-flto 
-DCMAKE_INTDIR=\"Release-iphoneos\" 
-DMBGL_USE_GLES2=1 
-DRAPIDJSON_HAS_STDSTRING=1 
-fstrict-aliasing 
-fembed-bitcode 
-ftemplate-depth=1024 
-fno-rtti 
-Qunused-arguments 
-fcolor-diagnostics 
-DNDEBUG 
-DNDEBUG 
-fPIC 
-fvisibility=hidden 
-fvisibility-inlines-hidden 
-fobjc-arc 
-std=c++14 
</pre>
</details>

**Comment by julianrex** [comment]
Looking at just the above compiler settings by configuration type for this repo (just for symbol_layer.cpp).

| Config                      | Size           | Opt.       | LTO                | RTTI     |
|--------------------|-----------|---------|--------------|--------|
| `MinSizeRel`           | 646192     | `-Os`    | `-flto=thin `  | none    |
| `Release `               | 991776      | `-O3`    | none              | none    |
| `RelWithDebInfo `  | 12637732 | `-O2`    | none              | none    |

Digging in further, it looks like the missing `-flto=thin` makes the biggest difference when compiling a single file like this.

**Comment by julianrex** [comment]
Looks like we might need a `MinSizeRelWithDebInfo`?

cc @brunoabinader @frederoni for visibility

**Comment by tmpsantos** [comment]
@julianmmardirosian another thing to try is `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`

**Comment by brunoabinader** [comment]
@julianrex @tmpsantos I noticed that CMake defaults to `-flto=thin`when `DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON`. However, from https://github.com/mapbox/mapbox-gl-native/pull/12502#issuecomment-408956255 I believe we should be using `-flto=full` instead of `-flto=thin`.

**Comment by julianrex** [comment]
Recent changes have reduced the size somewhat, but not to the low 4mb range. 

Building with `MinSizeRel` (with `MapboxMobileEvents.framework` built as `Release`) gives us a size of `4190128` (using the same technique as in the OP). So this looks like what we should use for our releases. (Note this was built with `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` as mentioned above, and `-flto=thin`)

However, `MinSizeRel` builds do not have debug symbols, and `-Oz` should bring the size down even more. In addition, with Xcode defaulting to use `Release` for target configurations it doesn't recognize, I wonder if we should use `Release` across the board for our releases (that include symbols)?

@tmpsantos @zugaldia @tobrun what do you think?

Also, @tmpsantos, have you done any investigation into `-flto=full`?

**Comment by tmpsantos** [comment]
> Also, @tmpsantos, have you done any investigation into `-flto=full`?

Yes, `-flto` alone defaults to `full` and that is what we use on Android.

I recently tweaked the next buildsystem, inspired by the conversation we had offline about the subject. I ended up removing `MinSizeRel` and now we should only support `Release` or `Debug`.

We should add all the additional flags we want to the `Release` build, this was already done for Android. We could do the same for iOS.

**Comment by julianrex** [comment]
>  I ended up removing MinSizeRel and now we should only support Release or Debug.

Is this ready for iOS too?

> We should add all the additional flags we want to the Release build, this was already done for Android. We could do the same for iOS.

Yes please! Can you let us know when this is done?

**Comment by tmpsantos** [comment]
It is done, just let me know the flags you want and we can add.

**Comment by julianrex** [comment]
Investigation is done; updating build configurations will be handled as part of https://github.com/mapbox/mapbox-gl-native-ios/issues/134.
