### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#7]
- [x] Update help pages - PR open
- [ ] Update website docs - PR open
~- [ ] Update `ios-sdk-examples`~
- [x] Update `mapbox-gl-native-ios` 
~- [ ] Any other repos?~

For the [Migrate bindings](https://github.com/mapbox/mapbox-gl-native-ios/milestone/1) milestone, we should create the PRs, but not merge them. This needs to wait till the repo is open.

**Comment by julianrex** [comment]
@jmkiley can you update this ticket with the current state please?

**Comment by jmkiley** [comment]
Hi! This is almost done. Just waiting on approval to merge a PR that allows updating the documentation from two repos.
