### ISSUE TITLE
Revert CI no-output timeout

### ISSUE THREAD

**Issue by julianrex** [mapbox/mapbox-gl-native-ios#71]
Follow on from https://github.com/mapbox/mapbox-gl-native-ios/pull/60:

We had to bump the CI no-output timeout to 20m (up from 5m) - this should be considered a short-term measure.

Let's investigate a solution here - which may involve disabling parallel builds for the relevant schemes.

**Comment by misterkerry** [comment]
@julianrex: trying various versions with 0m timeouts and increments up to 20m

**Comment by misterkerry** [comment]
@julianrex trying this config all week...see if it passes.
![Screen Shot 2020-04-27 at 6 58 26 PM](https://user-images.githubusercontent.com/62082137/80443422-0a89ec00-88c4-11ea-937f-b9f09ba631c5.png)
