### ISSUE TITLE
lineCap = "round" causes drawing a solid line instead of dashed

### ISSUE THREAD

**Issue by wojciech-kulik** [mapbox/mapbox-gl-native-ios#96]
### Steps to reproduce

 1. Using `Mapbox-iOS-SDK 5.5.0` add line style layer like this:
```
let layer = MGLLineStyleLayer(identifier: "my-style", source: source)
layer.lineColor = NSExpression(forConstantValue: UIColor.darkGray)
layer.lineWidth = NSExpression(forConstantValue: 4.0)
layer.lineCap = NSExpression(forConstantValue: "round")
layer.lineDashPattern = NSExpression(forConstantValue: [0.25, 1.5])
```

### Expected behavior

Dashed line should be drawn.

Screenshot from `5.4.0` version
![Screenshot 2019-12-11 at 10 50 04](https://user-images.githubusercontent.com/3128467/70610680-47e72900-1c04-11ea-81ba-e12bba1836af.png)

### Actual behavior

Solid line is drawn.

Screenshot from `5.5.0` version
![Screenshot 2019-12-11 at 10 48 42](https://user-images.githubusercontent.com/3128467/70610730-59c8cc00-1c04-11ea-8745-788e559f52f3.png)

### Configuration

**Mapbox SDK versions: 5.5.0** 
**iOSversions: 13.3** 
**Device/simulator models: all**
**Xcode version: 11.12.1**

**Comment by jmkiley** [comment]
Hi @wojciech-kulik - 

Thank you for the report! It looks like this was fixed by https://github.com/mapbox/mapbox-gl-native/pull/15947 in 5.6.0. Please let us know if you still see the issue in v5.6.0 or later.

**Comment by wojciech-kulik** [comment]
Hi,

I will try 5.6.0 once this issue is solved: https://github.com/mapbox/mapbox-navigation-ios/issues/2326
